name: GitHub Actions
# To get a trigger on every push in this repo in any branch
on: push

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps: 
      - name: Running Single Command in githubactions
        run : echo " Hello thus is my first githubaction workflow"
      - name : checking OS release for my github action hosted runner
        run : cat /etc/os-release
      - name : calling sleep
        run: sleep 20
         
  job2:
    name: Job2
    runs-on: ubuntu-latest
    steps:
      - name: checking the host name for runner
        run: hostname
      - name: Running Multiple steps 
        run: |
          echo " Hello I am Heamnth Vadde"
          echo " Cloud & DevOps Engineer"
          sleep 20

  job3:
    name: Job3
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Job with single Dependency
        run: sleep 10

  job4:
    name: Job4
    needs: [job2, job3, job1]
    runs-on: ubuntu-latest
    steps:
      - name : Job For Multiple Dependencies
        run : sleep10
        
    
